### ISSUE TITLE
Bug: discord 无法发送消息

### ISSUE THREAD

**Issue by idanran** [satorijs/satori#128]
复现：
```ts
ctx.middleware((session, next) => {
    session.bot.sendMessage(session.channelId, h(null, [h.text('1'), h.text('2')]))
    return next()
})
```

报错：
```
2023-07-05 17:50:59 [W] app TypeError: Cannot read properties of undefined (reading 'discord')
                            at DiscordMessageEncoder.getUrl (D:\develop\myrtus\node_modules\@satorijs\adapter-discord\src\message.ts:29:40)
                            at DiscordMessageEncoder.post (D:\develop\myrtus\node_modules\@satorijs\adapter-discord\src\message.ts:53:30)
                            at DiscordMessageEncoder.flush (D:\develop\myrtus\node_modules\@satorijs\adapter-discord\src\message.ts:141:16)
                            at DiscordMessageEncoder.send (D:\develop\myrtus\node_modules\@satorijs\core\src\message.ts:48:16)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by shigma** [comment]
已修复，请尝试最新版本。

**Comment by idanran** [comment]
> 已修复，请尝试最新版本。

好欸，问题解决了

**Comment by shigma** [comment]
你测试一下再关。我随手修的。

**Comment by idanran** [comment]
> 你测试一下再关。我随手修的。

测试了，暂时没见有问题。
