### ISSUE TITLE
[bug] 飞书群聊中用户发送消息时报错

### ISSUE THREAD

**Issue by Mcayear** [satorijs/satori#134]
```
2023-07-19 10:57:37 [W] sqlite > INSERT INTO `channel` (`flag`, `assignee`, `guildId`, `locales`, `name`, `activity`, `platform`, `id`) VALUES (0, 'cli_a42bb1523638900c', NULL, '', '', '{}', 'feishu', 'oc_512910569ca291eb21bc12ff8aeaef3e')
2023-07-19 10:57:37 [W] session 1
                        Error: UNIQUE constraint failed: channel.id, channel.platform
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:91:290)
                            at c.step (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:81:394)
                            at c.run (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:84:116)
                            at /koishi/node_modules/@minatojs/driver-sqlite/lib/index.js:384:80
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.js:352:20)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.js:384:41)
                            at #create (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.js:408:46)
                            at SQLiteDriver.create (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.js:311:62)
                            at Executable.execute (/koishi/node_modules/@minatojs/core/lib/index.cjs:385:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

飞书群聊中其它用户发送第一条消息会触发。

**Comment by MaikoTan** [comment]
I didn't understand what was going wrong, it looks like there is a unique key constraint conflict with existing ones on channel ID and channel platform (in this case it would be constant `lark`?).
But as far as I know, the channel ID would be varied between different chats in Lark. It is hard to debug with the database on my side, either.

我不明白出了什么问题，看起来与频道 ID 和频道平台上的现有键约束存在唯一的键约束冲突（在这种情况下，它将是恒定的“lark”？）。
但据我所知，Lark 中不同聊天的频道 ID 会有所不同。我这边的数据库也很难调试。

**Comment by shigma** [comment]
这个问题可能是 Koishi 的问题，与飞书适配器无关。不过我也比较难复现。
