### ISSUE TITLE
钉钉发送图片报错

### ISSUE THREAD

**Issue by LoneyKnight** [satorijs/satori#154]
使用novelai插件生成图片发送到私聊报错.
```
2023-09-06 12:50:22 [W] session Error: [413] "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body><script>\nwith(document)with(body)with(insertBefore(createElement(\"script\"),firstChild))setAttribute(\"exparams\",\"category=&userid=&aplus&yunid=&asid=AQAAAAAPBfhkJvtxIwAAAAAv6/tn0uvDEA==\",id=\"tb-beacon-aplus\",src=(navigator.userAgent.match(/iPhone|iPad|iPod|Android|AliApp|Yunos|cyclone/i)?\"//d.alicdn.com/alilog/mlog/aplus/203219514\":\"//g.alicdn.com/alilog/mlog/aplus_v2\")+\".js\")\n</script>\n\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr/>Powered by DingTalk/1.0.0<hr><center>tengine</center>\r\n</body>\r\n</html>\r\n"
                            at _Internal.<computed> [as batchSendOTO] (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:348:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _DingtalkMessageEncoder.sendMessage (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:162:57)
                            at async _DingtalkMessageEncoder.flush (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:155:7)
                            at async _DingtalkMessageEncoder.send (D:\koishi\koishi-app\node_modules\@satorijs\core\lib\index.cjs:460:5)
                            at async iterate (D:\koishi\koishi-app\node_modules\koishi-plugin-novelai\lib\index.js:429:32)
                            at async _Command.<anonymous> (D:\koishi\koishi-app\node_modules\koishi-plugin-novelai\lib\index.js:440:17)
                            at async Array.<anonymous> (D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1677:14)
                            at async _Command.execute (D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1692:22)
                            at async D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:2294:22
```

**Comment by shigma** [comment]
钉钉不支持发送这么大的图片

**Comment by LoneyKnight** [comment]
缩小后
```
2023-09-07 10:46:00 [W] session Error: [400] {"code":"InvalidmsgParam","requestid":"D3C889A9-F733-73DE-A228-09C465C2E5D7","message":"Specified parameter msgParam is not valid."}
                            at _Internal.<computed> [as batchSendOTO] (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:348:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _DingtalkMessageEncoder.sendMessage (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:162:57)
                            at async _DingtalkMessageEncoder.flush (D:\koishi\koishi-app\node_modules\@satorijs\adapter-dingtalk\lib\index.js:155:7)
                            at async _DingtalkMessageEncoder.send (D:\koishi\koishi-app\node_modules\@satorijs\core\lib\index.cjs:460:5)
                            at async iterate (D:\koishi\koishi-app\node_modules\koishi-plugin-novelai\lib\index.js:429:32)
                            at async _Command.<anonymous> (D:\koishi\koishi-app\node_modules\koishi-plugin-novelai\lib\index.js:440:17)
                            at async Array.<anonymous> (D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1677:14)
                            at async _Command.execute (D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:1692:22)
                            at async D:\koishi\koishi-app\node_modules\@koishijs\core\lib\index.cjs:2294:22
```

**Comment by shigma** [comment]
应该是 bug。之后研究一下。
