### ISSUE TITLE
Bug: QQ频道回复机器人消息报错：TypeError: bot.getMessage is not a function

### ISSUE THREAD

**Issue by maxoyed** [satorijs/satori#176]
## 问题说明

![image](https://github.com/satorijs/satori/assets/25519245/c51b1e94-88d3-4555-b7b4-05ce96161898)

```shell
2023-11-01 20:20:40 [W] app TypeError: bot.getMessage is not a function
                            at decodeMessage (G:\project\bot\koishi-app\node_modules\@satorijs\adapter-qq\src\utils.ts:84:8)
                            at adaptSession (G:\project\bot\koishi-app\node_modules\@satorijs\adapter-qq\src\utils.ts:123:59)
                            at WebSocket.<anonymous> (G:\project\bot\koishi-app\node_modules\@satorijs\adapter-qq\src\ws.ts:84:6)
                            at callListener (G:\project\bot\koishi-app\node_modules\ws\lib\event-target.js:290:14)
                            at WebSocket.onMessage (G:\project\bot\koishi-app\node_modules\ws\lib\event-target.js:209:9)
                            at WebSocket.emit (node:events:517:28)
                            at Receiver.receiverOnMessage (G:\project\bot\koishi-app\node_modules\ws\lib\websocket.js:1192:20)
                            at Receiver.emit (node:events:517:28)
                            at Receiver.dataMessage (G:\project\bot\koishi-app\node_modules\ws\lib\receiver.js:560:14)
                            at G:\project\bot\koishi-app\node_modules\ws\lib\receiver.js:511:23
```

测试发现QQ群没有此问题，看了下QQ群这边接收到的原始 ws 数据包中连 `message_reference` 这个字段都没有（QQ频道有 `message_reference` 字段）

## 依赖版本
koishi: 4.15.3
@satorijs/core: 3.1.1
@satorijs/adapter-qq: 4.1.3

**Comment by shigma** [comment]
此问题在最新版本中已经得到修复。
