### ISSUE TITLE
钉钉收不到消息

### ISSUE THREAD

**Issue by gyf9835** [satorijs/satori#178]
adapter-dingtalk 版本2.0.3
协议ws

内部群聊时收不到任何消息，并且没有任何日志
私聊机器人时可以接收消息，会报以下错误，无回复消息

```log
2023-11-13 22:05:27 [W] session 帮助
                        TypeError: Cannot read properties of undefined (reading 'type')
                            at get isDirect [as isDirect] (/koishi/node_modules/@satorijs/core/lib/index.cjs:85:31)
                            at _Processor.attach (/koishi/node_modules/@koishijs/core/lib/index.cjs:1009:20)
                            at next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:69)
                            at /koishi/node_modules/@koishijs/plugin-bind/lib/index.js:87:14
                            at next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:69)
                            at /koishi/node_modules/@koishijs/plugin-login/lib/index.js:125:16
                            at next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:69)
                            at _Processor._handleMessage (/koishi/node_modules/@koishijs/core/lib/index.cjs:1064:28)
                            at Proxy.emit (/koishi/node_modules/cordis/lib/index.cjs:108:16)
                            at _DingtalkBot.dispatch (/koishi/node_modules/@satorijs/core/lib/index.cjs:325:20)
```

**Comment by shigma** [comment]
已修复，请更新到最新版再次尝试。

**Comment by SyraTi** [comment]
接入钉钉时 遇到同样错误

**Comment by SyraTi** [comment]
> 版本：2.0.5 还是不行，问题和之前一样，但是报错不同了
> 
> 内部群聊时收不到任何消息，并且没有任何日志 私聊机器人时可以接收消息，会报以下错误，无回复消息
> 
> ```
> 2023-11-21 09:04:19 [W] session Error: [400] {"code":"MissingString","requestid":"9CDAE3AE-B54C-7C8E-9D24-D4D71F1B08C6","message":"String is mandatory for this action."}
>                             at _Internal.<computed> [as batchSendOTO] (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:357:21)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>                             at async _DingtalkMessageEncoder.sendMessage (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:166:57)
>                             at async _DingtalkMessageEncoder.flush (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:159:7)
>                             at async _DingtalkMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:580:5)
>                             at async _DingtalkBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:341:22)
>                             at async _Processor._handleMessage (/koishi/node_modules/@koishijs/core/lib/index.cjs:1065:9)
> ```
接入钉钉时 遇到同样错误

**Comment by shigma** [comment]
@SyraTi @gyf9835 劳烦二位尝试 2.0.6

**Comment by CaoMeiYouRen** [comment]
> @SyraTi @gyf9835 劳烦二位尝试 2.0.6

hi, 我试了下 2.0.6 版本，报同样的错。
```txt
session Error: [400] {"code":"MissingString","requestid":"708B34D0-C2EF-744E-95EB-A98B749FC1CF","message":"String is mandatory for this action."}
                            at _Internal.<computed> [as batchSendOTO] (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:357:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _DingtalkMessageEncoder.sendMessage (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:166:57)
                            at async _DingtalkMessageEncoder.flush (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:159:7)
                            at async _DingtalkMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:577:5)
                            at async _DingtalkBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:338:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2178:7
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2074:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:16)
```

**Comment by gyf9835** [comment]
> @SyraTi @gyf9835 劳烦二位尝试 2.0.6

私聊：正常
群聊：可接收@信息，普通群消息不会回复，不知是否是钉钉的特性
![Screenshot_2023-11-26-21-34-30-225_com alibaba android rimet-edit](https://github.com/satorijs/satori/assets/24644280/a24e1efb-96ae-4dcf-aba6-d49aa678ff8b)

**Comment by shigma** [comment]
@gyf9835 钉钉的群聊是只能收 at 的

**Comment by CaoMeiYouRen** [comment]
> @gyf9835 钉钉的群聊是只能收 at 的

我把依赖更新到最新的也还是不行。
![image](https://github.com/satorijs/satori/assets/40430746/f66ff21c-e861-4f91-a035-dd09ea10ff40)
![image](https://github.com/satorijs/satori/assets/40430746/bc7b8752-3751-45f2-afb7-056c4b4e8372)

**Comment by shigma** [comment]
别担心，只要你们还遇到问题，我们就会继续看的

**Comment by gyf9835** [comment]
> @gyf9835 钉钉的群聊是只能收 at 的

好的，那我这边已经没有问题了，非常感谢

**Comment by SyraTi** [comment]
> @SyraTi @gyf9835 劳烦二位尝试 2.0.6

我这边也没问题了，感谢修复！

**Comment by CaoMeiYouRen** [comment]
> @CaoMeiYouRen 别担心，只要你们还遇到问题，我们就会继续看的

查了下请求日志，是这样的。

![QQ截图20231127143824](https://github.com/satorijs/satori/assets/40430746/5aa2f63a-9e41-415d-9aad-8da2b5e6dcf1)

**Comment by shigma** [comment]
所以这个问题仍然能够稳定复现吗？

**Comment by CaoMeiYouRen** [comment]
> 所以这个问题仍然能够稳定复现吗？

是的

**Comment by SyraTi** [comment]
> > 我这边也没问题了，感谢修复！
> 
> 那上面 2 天前那个问题是怎么解决的？

我升级到2.0.6就好了，步骤大概是
1. ```yarn dep```
2. 在koishi控制台发现还是2.0.5, 然后在下拉框更新到了2.0.6
3. 问题不再复现

**Comment by CaoMeiYouRen** [comment]
> 所以这个问题仍然能够稳定复现吗？

不知道为什么，今天试了下最新的2.0.6又可以了，我这边也没问题了。

**Comment by XxLittleCxX** [comment]
> > 所以这个问题仍然能够稳定复现吗？
> 
> 是的

你是使用什么指令 / 调用什么 API 时触发的报错，是否方便留个联系方式

**Comment by CaoMeiYouRen** [comment]
> > > 所以这个问题仍然能够稳定复现吗？
> > 
> > 
> > 是的
> 
> 你是使用什么指令 / 调用什么 API 时触发的报错，是否方便留个联系方式

之前的话是使用`help`命令（其他命令没有测试）
目前已经fix了，没有复现这个问题了

**Comment by shigma** [comment]
那我就先 close 了，如果之后遇到问题可以再联系。

**Comment by XxLittleCxX** [comment]
@gyf9835 发不了本地图片是钉钉 API 限制，可通过 `server-temp` 和配置 `selfUrl` 解决

**Comment by gyf9835** [comment]
机器人运行了几天之后又收不到消息了

以下日志中，07:19:31的3个日志在上面反复出现，并不是我主动操作引起的
20:33:54 的日志是我发私聊消息引起的

koishi右下角的机器人状态中显示dingtalk为运行中

```log
2023-11-30 07:19:31 [W] app Error: getaddrinfo EAI_AGAIN api.dingtalk.com
                            at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
2023-11-30 07:19:31 [W] app Error: getaddrinfo EAI_AGAIN api.dingtalk.com
                            at AxiosError.from (/koishi/node_modules/axios/dist/node/axios.cjs:836:14)
                            at RedirectableRequest.handleRequestError (/koishi/node_modules/axios/dist/node/axios.cjs:3010:25)
                            at RedirectableRequest.emit (node:events:514:28)
                            at eventHandlers.<computed> (/koishi/node_modules/follow-redirects/index.js:14:24)
                            at ClientRequest.emit (node:events:514:28)
                            at TLSSocket.socketErrorListener (node:_http_client:495:9)
                            at TLSSocket.emit (node:events:514:28)
                            at emitErrorNT (node:internal/streams/destroy:151:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-11-30 07:19:31 [W] app Error: getaddrinfo EAI_AGAIN api.dingtalk.com
                            at request (/koishi/node_modules/cordis-axios/lib/index.js:153:21)
                            at http (/koishi/node_modules/cordis-axios/lib/index.js:172:30)
                            at _Internal.<computed> [as getAccessToken] (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:363:28)
                            at _DingtalkBot.refreshToken (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:426:38)
                            at listOnTimeout (node:internal/timers:573:17)
                            at process.processTimers (node:internal/timers:514:7)
2023-11-30 20:33:54 [W] app Error: read ETIMEDOUT
                            at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
2023-11-30 20:33:54 [W] app Error: read ETIMEDOUT
                            at AxiosError.from (/koishi/node_modules/axios/dist/node/axios.cjs:836:14)
                            at RedirectableRequest.handleRequestError (/koishi/node_modules/axios/dist/node/axios.cjs:3010:25)
                            at RedirectableRequest.emit (node:events:514:28)
                            at eventHandlers.<computed> (/koishi/node_modules/follow-redirects/index.js:14:24)
                            at ClientRequest.emit (node:events:514:28)
                            at TLSSocket.socketErrorListener (node:_http_client:495:9)
                            at TLSSocket.emit (node:events:514:28)
                            at emitErrorNT (node:internal/streams/destroy:151:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-11-30 20:33:54 [W] app Error: read ETIMEDOUT
                            at request (/koishi/node_modules/cordis-axios/lib/index.js:153:21)
                            at http (/koishi/node_modules/cordis-axios/lib/index.js:172:30)
                            at _Internal.<computed> [as getAccessToken] (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:363:28)
                            at _DingtalkBot.refreshToken (/koishi/node_modules/@satorijs/adapter-dingtalk/lib/index.js:426:38)
                            at listOnTimeout (node:internal/timers:573:17)
                            at process.processTimers (node:internal/timers:514:7)
```

**Comment by shigma** [comment]
> getaddrinfo EAI_AGAIN api.dingtalk.com

看起来是你的服务器网络环境存在问题。
