### ISSUE TITLE
Bug: adapter-discord的slash command中的变量(占位符？) 类型出现问题

### ISSUE THREAD

**Issue by itzdrli** [satorijs/satori#255]
示例1：
代码：
```
  ctx.command('getid <profLink:string>', '获取Steam ID', { authority: 0 })
    .action(async ({ session }, profLink) => {
      if (!profLink.startsWith("https://steamcommunity.com/")) {
        return '请输入正确的Steam个人资料链接';
      }
```
使用非 slash command 执行结果:
![image](https://github.com/satorijs/satori/assets/52338732/29175687-9dc5-41f2-a8e4-2ac88bd679a9)
同样的内容使用 slash command 执行结果: 
![image](https://github.com/satorijs/satori/assets/52338732/ab992410-01fb-452d-99da-efee7f7e5782)
报错：
```
2024-04-03 18:03:42 [W] command getid
                        TypeError: Cannot read properties of undefined (reading 'startsWith')
                            at Command.<anonymous> (/home/dev/koishi/external/cs-lookup/src/commands/getid.ts:7:21)
                            at Array.<anonymous> (/home/dev/koishi/node_modules/@koishijs/core/src/command/command.ts:287:27)
                            at Object.argv.next (/home/dev/koishi/node_modules/@koishijs/core/src/command/command.ts:299:27)
                            at Command.execute (/home/dev/koishi/node_modules/@koishijs/core/src/command/command.ts:303:33)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at <anonymous> (/home/dev/koishi/node_modules/@koishijs/core/src/session.ts:396:22)
                            at Proxy.withScope (/home/dev/koishi/node_modules/@koishijs/core/src/session.ts:293:22)
```

示例2：
代码：[Github](https://github.com/itzdrli/koishi-plugin-helpdesk/blob/master/src/commands/close.ts)
使用非 slash command 执行结果:
![image](https://github.com/satorijs/satori/assets/52338732/8204de47-44e8-47f6-9ca2-318611aa5062)
使用 slash command 执行结果: 
![image](https://github.com/satorijs/satori/assets/52338732/ea25e117-9e3a-46fb-8e0d-04c5b520135f)
无报错

**Comment by shigma** [comment]
![image](https://github.com/satorijs/satori/assets/33423008/503d148b-7786-4d93-84c9-ac5774fc28a9)

因为你没有传这个参数啊……

还是说这个 Bug 指的是它应该返回「缺少参数」？

**Comment by itzdrli** [comment]
> 还是说这个 Bug 指的是它应该返回「缺少参数」？

不理解，为什么同样的代码可以在不使用slash command的时候正常执行呢

**Comment by shigma** [comment]
哦你传了 id。那我或者 LTC 晚点研究一下。
