### ISSUE TITLE
(bug) 从 feishu 转发图片至 red 时报错

### ISSUE THREAD

**Issue by Mcayear** [satorijs/satori#256]
环境信息：
```
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 QEMU Virtual CPU version 2.5+

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.3
    Console: 5.25.8
    Koishi Desktop: 1.0.2
```

插件信息：
```
adapter-red    3.1.0
adapter-lark     3.4.0
```

报错：
```
2024-04-04 12:18:20 [W] app TypeError: Cannot read properties of undefined (reading 'type')
                            at RedMessageEncoder.image (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:89:26)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async RedMessageEncoder.visit (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:263:17)
                            at async RedMessageEncoder.render (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:531:7)
                            at async RedMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:560:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:326:22)
```

**Comment by MaikoTan** [comment]
I am not sure how is Red adapter deal with image elements, but you have to configure the `selfUrl` for receiving resources elements properly, did you have them configured correctly?
