### ISSUE TITLE
尝试用QQ发送语音消息时报错session Error: Authorization Required

### ISSUE THREAD

**Issue by 738NGX** [satorijs/satori#287]
使用QQ官方机器人接口，发送其他消息（文字，图片等）均正常，只有使用music-downloadvoice-api这个插件点歌最后发送语音消息时发不出来。
完整的报错信息：
```
2024-06-28 23:32:17 [W] session Error: Authorization Required
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:345:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.file (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:414:49)
                            at async QQMessageEncoder.visit (/koishi/node_modules/@satorijs/adapter-qq/lib/index.cjs:1157:24)
                            at async QQMessageEncoder.render (/koishi/node_modules/@satorijs/core/lib/index.cjs:586:7)
                            at async QQMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:615:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:346:22)
                            at async Command.<anonymous> (/koishi/node_modules/koishi-plugin-music-downloadvoice-api/lib/index.js:246:9)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1114:14)
                            at async Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1128:22)
```
adapter-qq设置：
![image](https://github.com/satorijs/satori/assets/79038651/180feefc-f42a-434b-88b3-fa8fe298d5d1)

**Comment by 738NGX** [comment]
相同的设置在Windows本地模板项目测试是正常发的出语音的，但是迁移到服务器docker之后就会报这个错误

**Comment by idranme** [comment]
可能跟服务器所在地区有关

**Comment by shigma** [comment]
如果你本地能发就说明插件工作正常，建议转到 discussion 或论坛继续讨论。
