### ISSUE TITLE
adapter-qq 更新至 4.19.1 ，websocket 连接方式 依然报错 【当前配置项不满足约束，请检查配置！】

### ISSUE THREAD

**Issue by shangxueink** [satorijs/satori#331]
我是从 https://github.com/satorijs/satori/issues/330  过来的咪

issue 被 close 了，但是问题没有解决

---

我看到了 adapter-qq 的 4.19.1 的更新

但是我翻阅了 ->  https://www.npmjs.com/package/@satorijs/adapter-qq?activeTab=code

但是似乎在 @satorijs/adapter-qq 的 index.cjs 里面，`websocket` 配置项还是 `.required()`

其中 第 549 行 左右

```
((WsClient2) => {
  WsClient2.Options = import_core2.Schema.intersect([
    import_core2.Schema.object({
      protocol: import_core2.Schema.const("websocket").required()
    }),
    import_core2.Adapter.WsClientConfig
  ]);
})(WsClient || (WsClient = {}));
```
发现其中还是
```
protocol: import_core2.Schema.const("websocket").required()
```

---

实测也是 不可开启 websocket 的状态

> 可是我一个小火箭 更新到 4.19.1 问题依然存在

---

我尝试强制退回到 4.18.6 改为 websocket，在 使用 websocket 连接的 插件开启的状态下 小火箭更新了一下

发现日志报错（其中部分配置项内容遮挡处理）
```

2024-12-25 21:50:52 [E] app TypeError: expected { protocol: "websocket" } & { retryTimes?: number, retryInterval?: number, retryLazy?: number } | { protocol: "webhook", path?: string } but got {"type":"public","authType":"bot","intents":["GUILDS","GUILD_MEMBERS","GUILD_MESSAGE_REACTIONS","DIRECT_MESSAGES","OPEN_FORUMS_EVENT","AUDIO_OR_LIVE_CHANNEL_MEMBER","USER_MESSAGE","INTERACTIONS","MESSAGE_AUDIT","AUDIO_ACTION","PUBLIC_GUILD_MESSAGES"],"id":"102069859","secret":"PoEe...........................b4X0","token":"0QL.........vvcUx"}
                            at C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:457:9
                            at Function.resolve (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:226:12)
                            at C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:462:26
                            at Function.resolve (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:226:12)
                            at schema (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\schemastery\lib\index.cjs:11:19)
                            at resolveConfig (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:94:54)
                            at Proxy.plugin (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:1048:18)
                            at Proxy.forkPlugin (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\loader\lib\shared.js:279:19)
                            at async Proxy.reload (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\loader\lib\shared.js:306:16)
```

看起来是预期的配置中需要有一个 `protocol` 属性，它的值应该是 `"websocket"` 或 `"webhook"`，但实际传入的对象中没有 `protocol` 属性。

---

在 4.19.1 版本的 @satorijs/adapter-qq ，我手动修改了 一下index.cjs第549行的内容
```
node_modules/@satorijs/adapter-qq/lib/index.cjs
```
我将 
```
protocol: import_core2.Schema.const("websocket").required()
```

修改为了

```
protocol: import_core2.Schema.const("websocket")
```

重启koishi之后 发现问题得以解决

![image](https://github.com/user-attachments/assets/7206b46c-1c18-4647-ba23-fcb0ac2767fe)

---

期望的行为：

小火箭之后，应该可以继续使用 websocket 协议

并且 同时支持 webhook 协议的使用

---

**Comment by shigma** [comment]
好像忘记构建了，看下 4.19.2？

**Comment by shangxueink** [comment]
好哦，成功了 哦

---


![image](https://github.com/user-attachments/assets/9530f133-c021-471b-9b75-ce9afcdd0dd0)
