### ISSUE TITLE
Bug: proxyAgent does not handle http proxy correctly

### ISSUE THREAD

**Issue by MirrorCY** [satorijs/satori#39]
### Describe the bug

Parametric `proxyAgent` does not work well with http proxies. It appears that the proxy agent transforms the endpoint port to the proxy protocol default port. 
But here's the weird thing, it works good with socks5 proxy.​ (it doesn't convert port to 1080)
For example:
proxyAgent: http://192.168.1.1:7890
endpoint url: https://api.telegram.org    (:443)
actually visited endpoint url: https://api.telegram.org:80

在适配器插件中配置 http 代理似乎会把访问的端口转换为代理协议的默认端口，比如使用 http://192.168.1.1:7980 作为代理时访问 https://api.telegram.org 会在代理的日志中发现，实际访问的地址为 https://api.telegram.org:80 
但是使用 socks://192.168.1.1:7890 就不会出现这个问题，遇到这个问题的小伙伴可以先这样用顶一顶。

### Steps to reproduce

Install and configure Fndroid/clash_for_windows_pkg 0.20.6
open `Allow LAN`
configure `proxyAgent` an http proxy in @koishijs/plugin-adapter-telegram, e.g. `http://192.168.1.1:7890`
start adapter and see connection in clash

### Expected behavior

follow endpoint port when using proxy

### Screenshots

![WQ`2GMR {V2FTXAQ41 G260](https://user-images.githubusercontent.com/37006258/199826247-5f5dc929-89dd-4d2d-9dae-880464cbfe2a.png)

### Versions

- OS: Ubuntu-serever 22.04 docker
- Proxy OS: windows10 10.0.19044
- Koishi version: 4.9.9
- adapter-telegram version: 3.5.0
- clash_for_windows_pkg version: 0.20.6

**Comment by MirrorCY** [comment]
https://github.com/koishijs/koishi/issues/835

**Comment by shigma** [comment]
> 到现在都没有修复吗？

使用 socks://127.0.0.1:7890 即可。

**Comment by lengxii** [comment]
为啥我国外机器 也访问不了 ，还要设置代理吗？
at Timeout.internalConnectMultipleTimeout (node:net:1707:38)
at listOnTimeout (node:internal/timers:583:11)
at process.processTimers (node:internal/timers:519:7)
2024-09-24 02:09:53 [W] app Error: connect ENETUNREACH 2001:67c:4e8:f004::9:443 - Local (:::0)
at internalConnectMultiple (node:net:1182:16)
at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
at listOnTimeout (node:internal/timers:583:11)
at process.processTimers (node:internal/timers:519:7)
2024-09-24 02:09:53 [W] app TypeError: fetch failed
at node:internal/deps/undici/undici:13178:13
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:184:26)
at async _Internal.<computed> [as getMe] (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:70:26)
at async _TelegramBot.getLogin (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:923:18)
at async _TelegramBot.initialize (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:863:5)
2024-09-24 02:09:53 [W] app Error: fetch https://api.telegram.org/bot7787305583:AAHyk3W_dfJ83Vh88MQXY0nTB8jVb5NxcWE/getMe failed
at /koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:319:23
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:184:26)
at async _Internal.<computed> [as getMe] (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:70:26)
at async _TelegramBot.getLogin (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:923:18)
at async _TelegramBot.initialize (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:863:5)

**Comment by shigma** [comment]
@lengxii 

您的评论中泄露了 bot token，我已经将其删除。考虑到安全问题，请尽快更换你的 bot token。

如果您无法访问某个地址，可以尝试设置代理或者使用抓包工具进行测试，这大概率并非 koishi 或者 satori 方面的问题。
