### ISSUE TITLE
bug: discord 适配器发送图片时报错

### ISSUE THREAD

**Issue by MirrorCY** [satorijs/satori#58]
在 discord 平台使用 rryth 或 novelai 插件绘制图片
图片无法发出，日志中出现报错 `[W] session TypeError: (0 , import_cosmokit.base64ToArrayBuffer) is not a function`
未明确复现方法
删除 node_modules 与 yarn.lock 后重新 yarn 可以解决此问题
已在 koishi-desktop 与 docker 环境中遇到此问题

版本：
- koishi 4.10.10
- discord adapter 3.3.3

截图：
![image](https://user-images.githubusercontent.com/37006258/210151877-e306ee29-699a-4438-8e9c-8387beaa3ca6.png)

日志：
```
2023-01-01 00:56:11 [W] session TypeError: (0 , import_cosmokit.base64ToArrayBuffer) is not a function
                            at Quester.file (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@satorijs\satori\lib\index.js:89:58)
                            at DiscordMessenger.sendAsset (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@satorijs\adapter-discord\lib\index.js:251:46)
                            at DiscordMessenger.visit (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@satorijs\adapter-discord\lib\index.js:367:18)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async DiscordMessenger.render (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@satorijs\core\lib\index.cjs:395:7)
                            at async DiscordMessenger.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@satorijs\core\lib\index.cjs:405:5)
                            at async _Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\koishi-plugin-rryth\lib\index.js:218:21)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@koishijs\core\lib\index.cjs:1512:14)
                            at async _Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@koishijs\core\lib\index.cjs:1527:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default2\node_modules\@koishijs\core\lib\index.cjs:2052:22
```
新年快乐

**Comment by shigma** [comment]
更新到最新版本可解决此问题。
